run_name: Mimir-1B-ddp-demo
seed: 9313
dry_run: false

aim:
  repo: /leonardo/home/userexternal/jschneid/fast/OLMo/
  experiment: ${run_name} # null to deactivate
  sync_repo: null #aim://aim.caracal.imada.sdu.dk
  sync_args:
    repeat: 60
    verbosity: 2
  log_interval: 1

model:
  d_model: 2048
  n_heads: 16
  n_layers: 16
  mlp_ratio: 8
  weight_tying: true
  alibi: false
  rope: true
  rope_theta: 500000
  flash_attention: true
  attention_dropout: 0.0
  include_bias: false
  block_type: sequential
  layer_norm_type: rms
  layer_norm_with_affine: true
  layer_norm_eps: 1e-6
  bias_for_layer_norm: false
  attention_layer_norm: true
  attention_layer_norm_with_affine: true
  norm_after: true
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  vocab_size: 32768
  embedding_size: 32768
  eos_token_id: 1
  pad_token_id: 1
#  vocab_size: 100278
#  embedding_size: 100352
#  eos_token_id: 100257
#  pad_token_id: 100277
  init_device: cuda
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3

softmax_auxiliary_loss: true
auxiliary_loss_multiplier: 1e-5
fused_loss: true

compile: null
#  mode: default

optimizer:
  name: demo
  learning_rate: 3.0e-4
  weight_decay: 0.0
  eps: 1e-8
  decay_norm_and_bias: false
  decay_embeddings: false
  compression_decay: 0.99
  compression_topk: 32
  compression_chunk: 64
  metrics_log_interval: 1

scheduler:
  name: cosine_with_warmup
  units: tokens
  t_warmup: 8388608000
  t_max: 5e12
  alpha_f: 0.1
  warmup_min_lr: 0.0

tokenizer:
  identifier: tokenizers/mistral.json
#  identifier: tokenizers/allenai_dolma2.json
  truncate_direction: right

save_folder: ${oc.env:SCRATCH}/Mimir/checkpoints/${run_name}-${oc.env:JOBID}
save_overwrite: false

save_interval: 250
save_interval_ephemeral: null
save_num_checkpoints_to_keep: 9
sharded_checkpointer: olmo_core

save_interval_unsharded: 10000
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

max_duration: 250
global_train_batch_size: 1024
device_train_microbatch_size: 4

precision: amp_bf16

distributed_strategy: ddp
ddp:
  grad_sync_mode: "none"

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

gen1_gc_interval: 1

eval_interval: ${save_interval}
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  # - label: all-small-ppl-validation
  #   data:
  #     num_workers: 0
  #     drop_last: true
  #     # generate_doc_lengths: true
  #     memmap_dtype: uint32
  #     datasets:
  #       c4_en-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/c4_en/val/part-0-00000.npy
  #       dolma_books-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_books/val/part-0-00000.npy
  #       dolma_common-crawl-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_common-crawl/val/part-0-00000.npy
  #       dolma_pes2o-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_pes2o/val/part-0-00000.npy
  #       dolma_reddit-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_reddit/val/part-0-00000.npy
  #       dolma_stack-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_stack/val/part-0-00000.npy
  #       dolma_wiki-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_wiki/val/part-0-00000.npy
  #       ice-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/ice/val/part-0-00000.npy
  #       m2d2_s2orc-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/m2d2_s2orc/val/part-0-00000.npy
  #       pile-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/pile/val/part-0-00000.npy
  #       wikitext_103-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/wikitext_103/val/part-0-00000.npy

  ##########################
  # Downstream evaluations #
  ##########################
  - label: piqa
    type: downstream

  - label: hellaswag
    type: downstream

  - label: winogrande
    type: downstream

  - label: openbook_qa
    type: downstream

  - label: boolq
    type: downstream

  - label: sciq
    type: downstream

  - label: arc_easy
    type: downstream

  - label: arc_challenge
    type: downstream

  - label: copa
    type: downstream

  - label: commonsense_qa
    type: downstream

  - label: social_iqa
    type: downstream

  - label: mmlu_stem_var
    type: downstream

  - label: mmlu_humanities_var
    type: downstream

  - label: mmlu_social_sciences_var
    type: downstream

  - label: mmlu_other_var
    type: downstream

  - label: mmlu_stem_mc_5shot
    type: downstream

  - label: mmlu_humanities_mc_5shot
    type: downstream

  - label: mmlu_social_sciences_mc_5shot
    type: downstream

  - label: mmlu_other_mc_5shot
    type: downstream

  - label: mmlu_stem_mc_5shot_test
    type: downstream

  - label: mmlu_humanities_mc_5shot_test
    type: downstream

  - label: mmlu_social_sciences_mc_5shot_test
    type: downstream

  - label: mmlu_other_mc_5shot_test
    type: downstream

  - label: basic_arithmetic
    type: downstream

  - label: trivia_qa_wiki_ppl
    type: downstream

  - label: natural_qs_open_ppl
    type: downstream

  - label: arc_easy_ppl
    type: downstream

data:
  pad_direction: right
  # generate_doc_lengths: true
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  memmap_dtype: uint16
  timeout: 0
  instance_filter:
    repetition_max_period: 13
    repetition_min_period: 1
    repetition_max_count: 32
  paths:
    - ${oc.env:SCRATCH}/data/common_corpus/tokens-mistral/0/part-02-00005.npy
    - ${oc.env:SCRATCH}/data/common_corpus/tokens-mistral/0/part-09-00013.npy
    - ${oc.env:SCRATCH}/data/common_corpus/tokens-mistral/0/part-09-00014.npy
    - ${oc.env:SCRATCH}/data/common_corpus/tokens-mistral/0/part-00-00004.npy
    - ${oc.env:SCRATCH}/data/common_corpus/tokens-mistral/0/part-04-00014.npy
    - ${oc.env:SCRATCH}/data/common_corpus/tokens-mistral/0/part-03-00006.npy
    - ${oc.env:SCRATCH}/data/common_corpus/tokens-mistral/0/part-02-00012.npy
    - ${oc.env:SCRATCH}/data/dk_safe/tokens-mistral/part-01-00000.npy
    - ${oc.env:SCRATCH}/data/dk_safe/tokens-mistral/part-09-00000.npy
    - ${oc.env:SCRATCH}/data/dk_safe/tokens-mistral/part-02-00000.npy
    - ${oc.env:SCRATCH}/data/dk_safe/tokens-mistral/part-07-00000.npy
    - ${oc.env:SCRATCH}/data/dk_safe/tokens-mistral/part-00-00000.npy
    - ${oc.env:SCRATCH}/data/dk_safe/tokens-mistral/part-10-00000.npy
    - ${oc.env:SCRATCH}/data/dk_safe/tokens-mistral/part-11-00000.npy
    - ${oc.env:SCRATCH}/data/dk_safe/tokens-mistral/part-04-00000.npy
    - ${oc.env:SCRATCH}/data/dk_safe/tokens-mistral/part-05-00000.npy
    - ${oc.env:SCRATCH}/data/dk_safe/tokens-mistral/part-06-00000.npy
    - ${oc.env:SCRATCH}/data/dk_safe/tokens-mistral/part-08-00000.npy
    - ${oc.env:SCRATCH}/data/dk_safe/tokens-mistral/part-03-00000.npy
